version: 2.1
jobs:
  get-oidc:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: OIDC
          command: |
            circleci run oidc get --claims '{"aud": "WHATEVER"}'

workflows:
  get-oidc:
    jobs:
      - get-oidc
